### PR TITLE
update to track some changes in IPython 3

### LINKED ISSUE #48: runipy is broken in the current git master branch of IPython
Apparently there have been some API changes inside of IPython that have broken runipy:

```
goldbaum at ROUS in ~/Documents/runipy on master
± nosetests
/Users/goldbaum/Documents/ipython/IPython/nbformat/current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
E
======================================================================
ERROR: testRunNotebooks (test.TestRunipy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/goldbaum/Documents/runipy/test.py", line 50, in testRunNotebooks
    runner.run_notebook(True)
  File "/Users/goldbaum/Documents/runipy/runipy/notebook_runner.py", line 180, in run_notebook
    self.run_cell(cell)
  File "/Users/goldbaum/Documents/runipy/runipy/notebook_runner.py", line 87, in run_cell
    self.shell.execute(cell.input)
AttributeError: 'ZMQSocketChannel' object has no attribute 'execute'
-------------------- >> begin captured stdout << ---------------------
Clear Output.ipynb

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: DEBUG: Connecting to: tcp://127.0.0.1:57464
root: DEBUG: connecting shell channel to tcp://127.0.0.1:57461
root: DEBUG: Connecting to: tcp://127.0.0.1:57461
root: DEBUG: connecting iopub channel to tcp://127.0.0.1:57462
root: DEBUG: Connecting to: tcp://127.0.0.1:57462
root: DEBUG: connecting stdin channel to tcp://127.0.0.1:57463
root: DEBUG: Connecting to: tcp://127.0.0.1:57463
root: DEBUG: connecting heartbeat channel to tcp://127.0.0.1:57465
root: INFO: Running cell:
from IPython.display import clear_output

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 2.575s

FAILED (errors=1)
```

### PR DESCRIPTION
**Pull request by minrk**
- KernelClient API changes (use Client API already present in IPython < 3)
- stream msg changes
- minor change in test comparision normalization of tracebacks

closes #48

### CODE REVIEW

**Comment by stonebig** [comment]
any progress ?

**Comment by ngoldbaum** [comment]
I believe @minrk is pretty busy trying to get IPython 3.0 out.  It's also not clear to me if @paulgb is still around to merge this in.

**Comment by paulgb** [comment]
@ngoldbaum I was on hiatus from GitHub for a bit, but I'm still around. Unfortunately I haven't tracked the IPython 3 changes closely enough to figure this one out easily.

**Comment by minrk** [comment]
I'll try to get to this today or tomorrow.

**Comment by minrk** [comment]
This should work on IPython 3, now.

**Comment by stonebig** [comment]
thanks !

**Comment by paulgb** [comment]
Thanks @minrk. This is now available in runipy 0.1.2 from PyPi.

**Comment by stonebig** [comment]
you mean runipy 0.1.3 ?

**Comment by paulgb** [comment]
Yes, thanks for the correction.

**Pull request merged**
