### PR TITLE
Add deprecation warning for IPython 2.x and v2 notebook support

### PR DESCRIPTION
**Pull request by yuvipanda**
Partial fix for #78.

If ok, I'll probably make changes to have this natively read / operate on v4 notebooks and convert v3 notebooks on input/output (vs now, where it operates on v3 natively and converts to v4 on input/output)

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Just a comment that I do still use the v2 notebook support.

**Comment by jakirkham** [comment]
@ngoldbaum, what are you using iPython 2.x for (if you can share)?

**Comment by ngoldbaum** [comment]
The [documentation for the yt project](http://yt-project.org/doc/) (e.g. the quickstart notebooks). I'd like to update the notebooks we're evaluating to nbformat4, it's just it takes some time and there are other priorities that need to be taken care of.

**Comment by jakirkham** [comment]
In any event, while I am thinking about iPython 2.x deprecation. I don't like the ripping out of iPython 2.x quietly in a PR. I would prefer something like adding warnings for the iPython 2.x case that says we are deprecating iPython 2.x so users who may not be following the repo as closely see when they update that we are going this direction. Then after a release or so with the warnings, we remove it completely.

**Comment by jakirkham** [comment]
Thanks for sharing @ngoldbaum. So, this is mainly for examples or something more?

**Comment by ngoldbaum** [comment]
Yes, we use runipy to evaluate the example notebooks in our documentation during the docs build. It uses the sphinx extensions in this repository: https://github.com/ngoldbaum/RunNotebook

The most straightforward way to update our docs build to depend on nbformat4 would be to update RunNotebook to work with IPython4/Jupyter.

**Comment by yuvipanda** [comment]
Shall I rework this to emit warnings instead?

**Comment by jakirkham** [comment]
That's probably a good idea. We might need to do a bit of refactoring first. I would only want to see one warning for iPython 2.x and one for v2 notebook format. Otherwise, it is just way too noise. We could add a compat module just for iPython imports to make this easier.

**Comment by jakirkham** [comment]
Any chance you will have time to add some warnings, @yuvipanda? I'd like to start getting the word out that this deprecation is planned to see where we stand.

**Comment by ngoldbaum** [comment]
FWIW I don't use runipy at all anymore (we just use the evaluate preprocessor that comes with IPython now).

**Pull request closed without merging**
