### PR TITLE
Allow different kernels

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/paulgb/runipy/issues/16

Uses the API in iPython 3 and 4 to allow for this. May require a backport for iPython 2.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I can test this later. IMO v2 support should be dropped.

**Comment by hadim** [comment]
I would like to have this feature. Are you ok to merge this @paulgb ?

Also we would need to add a parameter and propagate the option.

**Comment by hadim** [comment]
Up ?

**Comment by hadim** [comment]
Is this project will maintened ? The last version is from October 2015.

**Comment by hadim** [comment]
For the record I have created a script similar to runipy : https://github.com/hadim/scijava-jupyter-kernel/blob/master/scripts/runipy.py

**Comment by paulgb** [comment]
Hi @hadim, sorry for the slow reply, I was away. Since Jupyter added execution to nbconvert (http://nbconvert.readthedocs.io/en/latest/execute_api.html), I'd suggest using that.

**Comment by hadim** [comment]
Thanks !

(I would suggest you to specify this on the README of this repo)

**Comment by paulgb** [comment]
Good point, it was in there but it should really be at the very top.

**Pull request closed without merging**
