### PR TITLE
PDF report generation

### PR DESCRIPTION
**Pull request by npyoung**
Added an argument to do PDF report generation instead of HTML. These options are mutually exclusive since only one template file can be specified, but this can be changed by allowing separate HTML and PDF templates.

This only works on IPython 3.x and 4.x right now, due to PDF generation being a post-processing step of the LaTeX output format in IPython 2.x rather than a full-fledged `PDFExporter`.

Also of note, the `nbconvert.writers` class is used to write the PDF rather than the `codecs` library as is done for HTML.

This is very WIP - please let me know what changes are needed before merging.

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...failures are weird. Not sure why that is happening. Definitely not related to your PR though.

**Comment by jakirkham** [comment]
This PR ( https://github.com/paulgb/runipy/pull/112 ) should fix the testing issues here. I'll let you know when it goes in.

**Comment by jakirkham** [comment]
The CI failures ended up being due to an upstream error that has since been resolved.

**Comment by npyoung** [comment]
Then are we ready to merge this?

**Comment by jakirkham** [comment]
Would be nice to see a test.

**Comment by jakirkham** [comment]
Also you mentioned this is still very WIP, what else about this is still WIP?

**Comment by npyoung** [comment]
WIP because I just didn't know if anyone felt that enabling multiple templates or having IPython 2.0 support for the PDF feature was important.

There are no tests for this PR because there are no tests for HTML output. How would you test PDF output? Make PDFs of each notebook then check that runipy can regenerate them byte-for-byte?

**Pull request closed without merging**
